### Schedule a lesson
POST localhost:3000/schedule-lesson
Content-Type: application/json

{
    "customer_id": "cus_Psk0ffeHK5hgBV",
    "amount": 123,
    "description": "lesson"
}

### Complete a lesson
POST localhost:3000/schedule-lesson
Content-Type: application/json

{
  "payment_intent_id": "cus_Psk0ffeHK5hgBV"
}

### Complete a lesson with amount
POST localhost:3000/complete-lesson-payment
Content-Type: application/json

{
  "payment_intent_id": "pi_3P3BPaHx6psTCyjy0OcsvRhR",
  "amount": 100
}

### Refund a lesson with amount
POST localhost:3000/complete-lesson-payment
Content-Type: application/json

{
  "payment_intent_id": "pi_3P37gnHx6psTCyjy1zLIxRnz",
  "amount": 100
}

### Get Stripe customer
GET https://api.stripe.com/v1/customers/cus_PseNw4MGYqWVuU/payment_methods
Authorization: Bearer sk_test_51P26yHHx6psTCyjymmZsE8wAAJzezOJV0IlqeoKHBODyCdPwDFGD93k74GJTXhp59D8MFNGipsKJjqyCzEZaWTPA000waYUiIE
Content-Type: application/x-www-form-urlencoded


### Create payment intent
POST https://api.stripe.com/v1/payment_intents
Authorization: Bearer sk_test_51P26yHHx6psTCyjymmZsE8wAAJzezOJV0IlqeoKHBODyCdPwDFGD93k74GJTXhp59D8MFNGipsKJjqyCzEZaWTPA000waYUiIE
Content-Type: application/x-www-form-urlencoded

amount=100&currency=usd
